"""
DIAGNOSTIC TYPES DEFINITION
Role: Provides foundational type-safe structures for the AI_Agent_OS diagnostic engine.
Integration: Used by diagnostic_engine.py and diagnostic_utils to enforce schema consistency.
"""

from __future__ import annotations
from typing import NamedTuple, Any, Dict, List, Optional

class DiagnosticCheckResult(NamedTuple):
    """
    Represents the outcome of an individual diagnostic check.
    
    Attributes:
        passed: Boolean indicating if the check succeeded.
        duration_ms: Execution time in milliseconds.
        message: Descriptive status message.
        metadata: Additional context or diagnostic data.
    """
    passed: bool
    duration_ms: float
    message: str
    metadata: Dict[str, Any]

class DiagnosticSummary(NamedTuple):
    """
    Aggregated metrics for a full diagnostic run.
    """
    total: int
    passed: int
    failed: int
    is_healthy: bool
    pass_rate: float

class DiagnosticTelemetry(NamedTuple):
    """
    System-level telemetry captured during diagnostic execution.
    """
    timestamp: str
    version: str
    node_id: str
    environment: str
    uptime_seconds: float

class DiagnosticReport(NamedTuple):
    """
    The final diagnostic report structure generated by the system.
    
    Attributes:
        status: Overall health status string (e.g., 'HEALTHY', 'CRITICAL').
        timestamp: ISO 8601 UTC timestamp.
        checks: Dictionary mapping check names to their results.
        summary: Aggregated metrics.
        telemetry: System environment telemetry.
    """
    status: str
    timestamp: str
    checks: Dict[str, DiagnosticCheckResult]
    summary: DiagnosticSummary
    telemetry: DiagnosticTelemetry

# Type alias for registry functions
# A check function returns a partial result (passed, message, metadata)
# The engine wraps this with duration and telemetry.
DiagnosticCheckFn = Any # Callable[[], Dict[str, Any]]